###########
# site.title, site.path, site.url

title: "Dr. Jekyll's Themes"

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
path:  /
url:   "http://drjekyllthemes.github.io"


########
# more settings

markdown: kramdown


##sass:
##  sass_dir: css
##   style:    expanded


include:
- _data

exclude:
- README.md


safe: true
lsi: false

